export type Lang = "id" | "en";

export const profile = {
  name: "Usman Ramadhan",
  initials: "UR",
  location: "Palembang, Indonesia",
  email: "usman@jolink.co.id",
  github: "https://github.com/wsprfme",
  githubHandle: "wsprfme",
  whatsapp: "https://wa.me/6281916848478",
  whatsappDisplay: "0819-1684-8478",
  jolink: "https://jolink.co.id",
  schoolSite: "https://smkn1bmr.sch.id",
  school: {
    id: "SMKN 1 Belitang Madang Raya",
    en: "SMKN 1 Belitang Madang Raya",
  },
  availability: {
    id: "Tersedia untuk full-time, freelance, dan kolaborasi",
    en: "Available for full-time, freelance, and collaboration",
  },
  role: {
    id: "Fullstack Web Developer",
    en: "Fullstack Web Developer",
  },
  tagline: {
    id: "Membangun website yang rapi, cepat, dan mudah dipakai.",
    en: "Building clean, fast, and easy to use websites.",
  },
  summary: {
    id: "Saya mengerjakan website dari tampilan sampai server dan deployment. Berbasis di Palembang, terbiasa kerja remote dan langsung dengan pengguna akhir.",
    en: "I build websites from interface to server and deployment. Based in Palembang, comfortable working remote and directly with end users.",
  },
};

export type SkillItem = { name: string; icon: string };

export const dict = {
  id: {
    nav: {
      about: "Tentang",
      skills: "Keahlian",
      experience: "Pengalaman",
      projects: "Proyek",
      achievement: "Penghargaan",
      contact: "Kontak",
      contactCta: "Hubungi saya",
      cv: "Unduh CV",
    },
    hero: {
      badge: "Tersedia untuk full-time, freelance, dan kolaborasi",
      greeting: "Halo, saya",
      ctaProjects: "Lihat proyek",
      ctaContact: "Hubungi saya",
      stats: [
        { value: "2", label: "Proyek live dipakai pengguna" },
        { value: "Juara 3", label: "LKS Web Technologies tingkat provinsi" },
        { value: "End-to-end", label: "Desain, kode, sampai deploy" },
      ],
      scroll: "Gulir ke bawah untuk detail",
    },
    about: {
      eyebrow: "Tentang",
      index: "01",
      title: "Siswa SMK yang berkembang lewat proyek dunia nyata.",
      desc: "Saya Usman Ramadhan, berdomisili di Palembang. Saat ini menempuh pendidikan kelas 3 TKJ di SMKN 1 Belitang Madang Raya, sambil mengelola Jolink dan mengerjakan berbagai proyek freelance.",
      photoCaption: "Foto formal",
      photoNote: "Background sudah transparan.",
      intro: [
        "Waktu harian saya terbagi dua: pagi hingga siang fokus sekolah, sisanya mengeksekusi kode. Tech stack utama saya mencakup React dan Next.js dengan TypeScript di frontend, serta Node.js, Go, Python, dan PHP di backend, yang kemudian saya deploy ke VPS Linux menggunakan Docker dan Coolify.",
        "Patokan saya sederhana: karya harus benar-benar digunakan oleh pengguna nyata. Mulai dari Sistem SPMB sekolah yang aktif diisi pendaftar, raihan Juara 3 LKS Web Technologies Tingkat Provinsi Sumatera Selatan 2026, platform Jolink dengan pengguna aktif harian, hingga bot dan tools kustom pesanan di Telegram dan Discord.",
      ],
      factsTitle: "Fakta singkat",
      rows: [
        ["Sekolah", "SMKN 1 Belitang Madang Raya"],
        ["Status", "Kelas 3 TKJ — Aktif"],
        ["Lokasi", "Palembang, Indonesia (WIB, Siap Remote)"],
        ["Ketersediaan", "Terbuka untuk Proyek Freelance dan Kontrak Remote"],
      ],
      pointsTitle: "Prinsip kerja",
      points: [
        { title: "Rapi Sejak Awal", desc: "Struktur folder terorganisir, histori commit jelas, dan kode gampang dilanjutkan oleh developer lain." },
        { title: "Optimasi Perangkat Low-End", desc: "Tampilan ringan, alur navigasi efisien, dan antarmuka yang ramah pengguna di berbagai spesifikasi smartphone." },
        { title: "Siap Operasional", desc: "Mandiri dalam melakukan deployment, memantau uptime sistem, hingga merespons kebutuhan pengguna dan klien secara langsung." },
      ],
      storyTitle: "Kenapa TKJ, Bukan RPL?",
      storyIcon: "/icons/growtopia.png",
      story: [
        "Berawal dari rasa penasaran saat kelas 1 SMP ketika sering bermain Growtopia. Muncul satu pertanyaan besar: bagaimana cara kerja sistem di balik game ini?",
        "Rasa penasaran itu mendorong saya melakukan riset mandiri tentang arsitektur privat server (GTPS). Dari sanalah saya pertama kali mengenal konsep server, client, database, dan jaringan. Pengalaman otodidak tersebut membuka pemahaman saya tentang bagaimana sebuah sistem saling terhubung.",
        "Saat mendaftar SMK, pilihan saya sudah bulat untuk mengambil jurusan TKJ demi memperdalam fondasi jaringan dan server. Pilihan ini terbukti tepat: pemahaman TKJ kini saya terapkan setiap hari untuk mengelola VPS, arsitektur jaringan, serta deployment platform Jolink dan proyek klien.",
      ],
    },
    skills: {
      eyebrow: "Keahlian",
      index: "02",
      title: "Peralatan yang saya pakai tiap hari.",
      desc: "Hanya yang benar-benar saya kuasai dan pernah saya bawa ke production.",
      groups: [
        {
          title: "Frontend",
          desc: "Tampilan dan interaksi",
          items: [
            { name: "React", icon: "/icons/react.svg" },
            { name: "Next.js", icon: "/icons/nextdotjs.svg" },
            { name: "TypeScript", icon: "/icons/typescript.svg" },
            { name: "Tailwind CSS", icon: "/icons/tailwindcss.svg" },
            { name: "PHP", icon: "/icons/php.svg" },
          ] as SkillItem[],
        },
        {
          title: "Backend",
          desc: "Logika dan data",
          items: [
            { name: "Node.js", icon: "/icons/nodedotjs.svg" },
            { name: "Go", icon: "/icons/go.svg" },
            { name: "Python", icon: "/icons/python.svg" },
            { name: "REST API", icon: "/icons/openapi.svg" },
            { name: "MySQL", icon: "/icons/mysql.svg" },
          ] as SkillItem[],
        },
        {
          title: "Ops",
          desc: "Deploy dan jalan",
          items: [
            { name: "Git", icon: "/icons/git.svg" },
            { name: "GitHub", icon: "/icons/github.svg" },
            { name: "Docker", icon: "/icons/docker.svg" },
            { name: "Coolify", icon: "/icons/coolify.svg" },
            { name: "Linux VPS", icon: "/icons/linux.svg" },
            { name: "Nginx", icon: "/icons/nginx.svg" },
          ] as SkillItem[],
        },
      ],
      note: "Butuh tools di luar daftar ini? Saya terbiasa menyesuaikan mengikuti kebutuhan proyek.",
    },
    experience: {
      eyebrow: "Pengalaman",
      index: "03",
      title: "Tempat saya belajar paling banyak.",
      items: [
        {
          period: "2025 — Sekarang",
          role: "Founder dan Developer",
          org: "Jolink — Layanan hosting game dan bot",
          bullets: [
            "Menjalankan layanan hosting: setup panel, billing, dan dukungan pelanggan.",
            "Mengelola VPS Linux, update berkala, dan pemantauan uptime.",
            "Mengurus hal non-teknis juga: harga, komplain, dan retensi pelanggan.",
          ],
          tags: ["Operasional", "Linux", "Dukungan pelanggan"],
        },
        {
          period: "2024 — Sekarang",
          role: "Freelance Developer — Custom tools dan web",
          org: "Klien via Telegram, Discord, dan komunitas",
          bullets: [
            "Mengerjakan pesanan custom tools dan website kecil dari pelanggan di Telegram, Discord, dan komunitas game.",
            "Terbiasa mengubah permintaan awam jadi spesifikasi teknis, deal harga, revisi, dan serah terima.",
            "Hasilnya dipakai langsung: tools automation, panel sederhana, dan landing page.",
          ],
          tags: ["Freelance", "Custom tools", "Remote"],
        },
        {
          period: "2025 — Saat ini",
          role: "Fullstack Developer",
          org: "SPMB SMKN 1 Belitang Madang Raya — Sistem penerimaan siswa",
          bullets: [
            "Membangun website pendaftaran dari nol sampai bisa dipakai pendaftar asli.",
            "Isinya: formulir pendaftaran, rekap data, dan halaman informasi.",
            "Dibuat mobile-first karena mayoritas akses dari HP orang tua dan siswa.",
          ],
          tags: ["Fullstack", "Formulir", "Mobile-first"],
          link: "https://smkn1bmr.sch.id",
        },
        {
          period: "2026",
          role: "Finalis — Juara 3 Provinsi",
          org: "LKS Web Technologies — Sumatera Selatan",
          bullets: [
            "Mewakili kabupaten ke tingkat provinsi, bertanding dengan peserta se-Sumsel.",
            "Mengerjakan studi kasus frontend dan backend dengan batas waktu.",
            "Sertifikat tersedia dan bisa diverifikasi lewat kontak di bawah.",
          ],
          tags: ["Kompetisi", "Web Technologies"],
        },
      ],
    },
    projects: {
      eyebrow: "Proyek",
      index: "04",
      title: "Dua yang paling menjelaskan cara saya kerja.",
      desc: "Satu bisnis yang berjalan, satu sistem yang dipakai publik. Keduanya live dan bisa dibuka sekarang.",
      items: [
        {
          name: "Jolink",
          tag: "Bisnis live",
          meta: "jolink.co.id — 2025 sampai sekarang",
          desc: "Layanan hosting game dan bot. Saya pegang semuanya: website order, setup server, dan support. Fokusnya sederhana: order gampang, server stabil, chat dibalas cepat.",
          stack: ["Linux VPS", "Panel hosting", "Billing", "Support"],
          link: "https://jolink.co.id",
          cta: "Buka website",
        },
        {
          name: "SPMB SMKN 1 Belitang Madang Raya",
          tag: "Sistem live",
          meta: "smkn1bmr.sch.id — 2025 sampai saat ini",
          desc: "Sistem penerimaan murid baru yang menggantikan pendaftaran manual. Alur dibuat pendek, bahasa dibuat sederhana, halaman ringan dibuka di HP.",
          stack: ["Fullstack web", "Formulir", "Mobile-first"],
          link: "https://smkn1bmr.sch.id",
          cta: "Buka website",
        },
      ],
      more: "Perlu penjelasan teknis atau akses repo privat? Tanya lewat WhatsApp, saya jelaskan alurnya.",
    },
    achievement: {
      eyebrow: "Penghargaan",
      index: "05",
      title: "Juara 3 LKS Web Technologies tingkat provinsi.",
      desc: "Lomba Kompetensi Siswa SMK, bidang Web Technologies, tingkat Provinsi Sumatera Selatan tahun 2026.",
      cardTitle: "Juara 3 — Web Technologies",
      cardDesc:
        "Bertanding mewakili kabupaten melawan peserta kabupaten dan kota se-Sumatera Selatan. Materi yang diujikan mencakup slicing tampilan, logika frontend, dan API backend.",
      uploadNote: "Sertifikat fisik dan file pindai tersedia. Minta salinannya lewat WhatsApp kalau perlu untuk verifikasi.",
      cta: "Minta salinan sertifikat",
    },
    contact: {
      eyebrow: "Kontak",
      index: "06",
      title: "Mari terhubung.",
      desc: "Senang bisa diskusi soal peluang kerja, proyek freelance, atau sekadar tukar pikiran soal web. Silakan hubungi lewat kanal yang paling nyaman, saya usahakan balas cepat di jam kerja WIB.",
      cards: [
        { label: "Email", value: "usman@jolink.co.id", href: "mailto:usman@jolink.co.id" },
        { label: "WhatsApp", value: "0819-1684-8478", href: "https://wa.me/6281916848478" },
        { label: "GitHub", value: "@wsprfme", href: "https://github.com/wsprfme" },
        { label: "Lokasi", value: "Palembang, ID", href: "https://wa.me/6281916848478" },
      ],
      formTitle: "Kirim pesan cepat",
      formDesc: "Isi nama dan pesan singkat, lalu pilih kirim lewat email atau WhatsApp.",
      namePh: "Nama Anda",
      msgPh: "Halo Usman, perkenalkan saya ... Saya ingin diskusi soal ...",
      sendEmail: "Kirim via email",
      sendWA: "Kirim via WhatsApp",
    },
    footer: {
      made: "Dibangun dengan Next.js dan Tailwind CSS",
      rights: "© 2026 Usman Ramadhan — Palembang, Indonesia.",
      top: "Kembali ke atas",
    },
  },
  en: {
    nav: {
      about: "About",
      skills: "Skills",
      experience: "Experience",
      projects: "Projects",
      achievement: "Award",
      contact: "Contact",
      contactCta: "Contact me",
      cv: "Download CV",
    },
    hero: {
      badge: "Available for full-time, freelance, and collaboration",
      greeting: "Hi, I'm",
      ctaProjects: "View projects",
      ctaContact: "Contact me",
      stats: [
        { value: "2", label: "Live projects with real users" },
        { value: "3rd place", label: "Provincial Web Technologies contest" },
        { value: "End-to-end", label: "Design, code, to deploy" },
      ],
      scroll: "Scroll down for details",
    },
    about: {
      eyebrow: "About",
      index: "01",
      title: "A vocational student growing through real-world projects.",
      desc: "I'm Usman Ramadhan, based in Palembang. Currently in grade 3 of TKJ at SMKN 1 Belitang Madang Raya, while running Jolink and taking on freelance projects.",
      photoCaption: "Formal photo",
      photoNote: "Background already transparent.",
      intro: [
        "My days split in two: mornings to afternoons for school, the rest for shipping code. My main stack is React and Next.js with TypeScript on the frontend, plus Node.js, Go, Python, and PHP on the backend, deployed to Linux VPS with Docker and Coolify.",
        "My benchmark is simple: work must be genuinely used by real users. From the school SPMB system filled in by actual applicants, 3rd place in Web Technologies at the 2026 South Sumatra provincial LKS, the Jolink platform with daily active users, to custom bots and tools ordered via Telegram and Discord.",
      ],
      factsTitle: "Quick facts",
      rows: [
        ["School", "SMKN 1 Belitang Madang Raya"],
        ["Status", "Grade 3 TKJ — Active"],
        ["Location", "Palembang, Indonesia (WIB, remote-ready)"],
        ["Availability", "Open for freelance and remote contract projects"],
      ],
      pointsTitle: "Work principles",
      points: [
        { title: "Tidy From the Start", desc: "Organized folder structure, clear commit history, code easy for other developers to continue." },
        { title: "Optimized for Low-End Devices", desc: "Lightweight views, efficient navigation, interfaces friendly across smartphone specs." },
        { title: "Ops-Ready", desc: "Independent in deployment, system uptime monitoring, and responding directly to user and client needs." },
      ],
      storyTitle: "Why TKJ Instead of RPL?",
      storyIcon: "/icons/growtopia.png",
      story: [
        "It started with curiosity in 7th grade when I played Growtopia a lot. One big question stuck: how does the system behind a game like this actually work?",
        "That curiosity pushed me into independent research on private server architecture (GTPS). That was my first encounter with servers, clients, databases, and networking. The self-taught experience opened my understanding of how systems connect.",
        "When enrolling in vocational school, my choice was set on TKJ to deepen networking and server fundamentals. It proved right: TKJ knowledge gets applied every day to manage VPS, network architecture, and deployments for Jolink and client projects.",
      ],
    },
    skills: {
      eyebrow: "Skills",
      index: "02",
      title: "Tools I use every day.",
      desc: "Only what I actually know and have taken to production.",
      groups: [
        {
          title: "Frontend",
          desc: "Interface and interaction",
          items: [
            { name: "React", icon: "/icons/react.svg" },
            { name: "Next.js", icon: "/icons/nextdotjs.svg" },
            { name: "TypeScript", icon: "/icons/typescript.svg" },
            { name: "Tailwind CSS", icon: "/icons/tailwindcss.svg" },
            { name: "PHP", icon: "/icons/php.svg" },
          ] as SkillItem[],
        },
        {
          title: "Backend",
          desc: "Logic and data",
          items: [
            { name: "Node.js", icon: "/icons/nodedotjs.svg" },
            { name: "Go", icon: "/icons/go.svg" },
            { name: "Python", icon: "/icons/python.svg" },
            { name: "REST API", icon: "/icons/openapi.svg" },
            { name: "MySQL", icon: "/icons/mysql.svg" },
          ] as SkillItem[],
        },
        {
          title: "Ops",
          desc: "Deploy and run",
          items: [
            { name: "Git", icon: "/icons/git.svg" },
            { name: "GitHub", icon: "/icons/github.svg" },
            { name: "Docker", icon: "/icons/docker.svg" },
            { name: "Coolify", icon: "/icons/coolify.svg" },
            { name: "Linux VPS", icon: "/icons/linux.svg" },
            { name: "Nginx", icon: "/icons/nginx.svg" },
          ] as SkillItem[],
        },
      ],
      note: "Need something outside this list? I usually pick it up as the project requires.",
    },
    experience: {
      eyebrow: "Experience",
      index: "03",
      title: "Where I learned the most.",
      items: [
        {
          period: "2025 — Present",
          role: "Founder and Developer",
          org: "Jolink — Game and bot hosting",
          bullets: [
            "Run a hosting service: panel setup, billing, and customer support.",
            "Manage Linux VPS, regular updates, and uptime monitoring.",
            "Handle the non-technical side too: pricing, complaints, retention.",
          ],
          tags: ["Operations", "Linux", "Customer support"],
        },
        {
          period: "2024 — Present",
          role: "Freelance Developer — Custom tools and web",
          org: "Clients via Telegram, Discord, and communities",
          bullets: [
            "Take orders for custom tools and small websites from customers on Telegram, Discord, and game communities.",
            "Used to turning plain requests into specs, agreeing on price, revisions, and handover.",
            "Output in real use: automation tools, simple panels, and landing pages.",
          ],
          tags: ["Freelance", "Custom tools", "Remote"],
        },
        {
          period: "2025 — Present",
          role: "Fullstack Developer",
          org: "SMKN 1 Belitang Madang Raya admission system",
          bullets: [
            "Built the registration website from zero until real applicants used it.",
            "Scope: registration form, data recap, and info pages.",
            "Mobile-first, since most access came from parents and students phones.",
          ],
          tags: ["Fullstack", "Forms", "Mobile-first"],
          link: "https://smkn1bmr.sch.id",
        },
        {
          period: "2026",
          role: "Finalist — 3rd place provincial",
          org: "LKS Web Technologies — South Sumatra",
          bullets: [
            "Represented the regency at provincial level against teams across S. Sumatra.",
            "Solved timed frontend and backend case studies.",
            "Certificate available and verifiable through the contact below.",
          ],
          tags: ["Competition", "Web Technologies"],
        },
      ],
    },
    projects: {
      eyebrow: "Projects",
      index: "04",
      title: "Two that explain how I work.",
      desc: "One running business, one system used by the public. Both live and openable now.",
      items: [
        {
          name: "Jolink",
          tag: "Live business",
          meta: "jolink.co.id — 2025 to present",
          desc: "Game and bot hosting service. I handle everything: order site, server setup, and support. The focus is simple: easy order, stable server, fast replies.",
          stack: ["Linux VPS", "Hosting panel", "Billing", "Support"],
          link: "https://jolink.co.id",
          cta: "Open website",
        },
        {
          name: "SMKN 1 Belitang Madang Raya admission",
          tag: "Live system",
          meta: "smkn1bmr.sch.id — 2025 to present",
          desc: "Admission system replacing manual registration. Short flow, plain language, light pages for phones.",
          stack: ["Fullstack web", "Forms", "Mobile-first"],
          link: "https://smkn1bmr.sch.id",
          cta: "Open website",
        },
      ],
      more: "Need technical details or private repo access? Ask on WhatsApp, I will walk you through it.",
    },
    achievement: {
      eyebrow: "Award",
      index: "05",
      title: "3rd place, provincial Web Technologies.",
      desc: "Vocational student competency contest, Web Technologies field, South Sumatra Province 2026.",
      cardTitle: "3rd place — Web Technologies",
      cardDesc:
        "Competed for the regency against cities and regencies across South Sumatra. Tested areas included layout slicing, frontend logic, and backend API.",
      uploadNote: "Physical certificate and scan available. Request a copy on WhatsApp if you need verification.",
      cta: "Request certificate copy",
    },
    contact: {
      eyebrow: "Contact",
      index: "06",
      title: "Let's connect.",
      desc: "Happy to chat about job opportunities, freelance projects, or just web in general. Reach me on whichever channel suits you, I reply fast during working hours WIB.",
      cards: [
        { label: "Email", value: "usman@jolink.co.id", href: "mailto:usman@jolink.co.id" },
        { label: "WhatsApp", value: "0819-1684-8478", href: "https://wa.me/6281916848478" },
        { label: "GitHub", value: "@wsprfme", href: "https://github.com/wsprfme" },
        { label: "Location", value: "Palembang, ID", href: "https://wa.me/6281916848478" },
      ],
      formTitle: "Quick message",
      formDesc: "Fill in your name and a short message, then send it via email or WhatsApp.",
      namePh: "Your name",
      msgPh: "Hi Usman, I'm ... I'd love to discuss ...",
      sendEmail: "Send via email",
      sendWA: "Send via WhatsApp",
    },
    footer: {
      made: "Built with Next.js and Tailwind CSS",
      rights: "© 2026 Usman Ramadhan — Palembang, Indonesia.",
      top: "Back to top",
    },
  },
} as const;

export type Dict = (typeof dict)["en"];
